/* empty css                      */import{i as d,a as S,S as v}from"./assets/vendor-YT4DRQk6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();window.global||(window.global=window);const q="48258923-bff14545616bbf92759f2c80c",P="https://pixabay.com/api/",$=document.querySelector("#searchForm"),m=document.querySelector("#gallery"),y=document.querySelector(".loader"),a=document.querySelector("#load-more"),u=document.querySelector(".load-more-loader");let p="",n=1;const c=40;y.style.display="none";a.style.display="none";u.style.display="none";async function f(){try{const o=await S.get(P,{params:{key:q,q:p,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:c}}),r=o.data.hits,i=o.data.totalHits;if(r.length===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(n*c>=i){d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a.style.display="none";return}const l=r.map(({largeImageURL:t,webformatURL:s,tags:g,likes:h,views:b,comments:w,downloads:L})=>`
          <div class="image-card">
            <a href="${t}" class="gallery-link" data-lightbox="gallery">
              <img src="${s}" alt="${g}" loading="lazy"/>
            </a>
            <div class="info">
              <p><span>Likes:</span> ${h}</p>
              <p><span>Views:</span> ${b}</p>
              <p><span>Comments:</span> ${w}</p>
              <p><span>Downloads:</span> ${L}</p>
            </div>
          </div>
        `).join("");m.insertAdjacentHTML("beforeend",l),new v(".gallery-link",{captionsData:"alt",captionDelay:250}).refresh(),n*c<i&&(a.style.display="block"),x()}catch(o){console.log(o)}finally{y.style.display="none",u.style.display="none"}}$.addEventListener("submit",async o=>{if(o.preventDefault(),p=document.querySelector("#form-input").value.trim(),!p){d.error({message:"Please enter a search term!",position:"topRight"});return}n=1,m.innerHTML="",a.style.display="none",y.style.display="inline-block",await f()});a.addEventListener("click",async()=>{u.style.display="inline-block",n+=1,await f()});function x(){const o=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
